import {satoshi, monument} from "./font";
import './globals.css'
import NavBar from "../app/components/NavBar";


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`relative ${monument.variable} ${satoshi.variable}`}>
        <NavBar/>
        {children}
        </body>
        </html>
    )
}
